apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-{{ .Release.Name }} # unique name based on the release name
spec:
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: mongodb-{{ .Release.Name }} # unique label based on the release name
  template:
    metadata:
      labels:
        app: mongodb-{{ .Release.Name }} # unique label based on the release name
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongodb.rootUsername }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-{{ .Release.Name }}-secret # unique name based on the release name
                  key: mongo-root-password
          volumeMounts:
            - name: mongodb-{{ .Release.Name }}-data # unique name based on the release name
              mountPath: /data/db
      volumes:
        - name: mongodb-{{ .Release.Name }}-data # unique name based on the release name
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-{{ .Release.Name }} # unique name based on the release name
spec:
  selector:
    app: mongodb-{{ .Release.Name }} # unique label based on the release name
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
