apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processing
spec:
  replicas: {{ .Values.microservices.orderProcessing.replicas }}
  selector:
    matchLabels:
      app: order-processing
  template:
    metadata:
      labels:
        app: order-processing
    spec:
      containers:
        - name: order-processing
          image: your-order-processing-image:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: {{ .Values.mongodb.connectionString }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: order-processing-logs
              mountPath: /var/log/order-processing
      volumes:
        - name: order-processing-logs
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: order-processing
spec:
  selector:
    app: order-processing
  ports:
    - name: http
      port: 3000
      targetPort: 3000
