apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-gateway
spec:
  replicas: {{ .Values.microservices.paymentGateway.replicas }}
  selector:
    matchLabels:
      app: payment-gateway
  template:
    metadata:
      labels:
        app: payment-gateway
    spec:
      containers:
        - name: payment-gateway
          image: talentplusio-payment-gateway:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: {{ .Values.mongodb.connectionString }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: payment-gateway-logs
              mountPath: /var/log/payment-gateway
      volumes:
        - name: payment-gateway-logs
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: payment-gateway
spec:
  selector:
    app: payment-gateway
  ports:
    - name: http
      port: 3000
      targetPort: 3000
